[package]
name = "cursive_secret_edit_view"
edition = "2024"
version = "0.1.0"

[dependencies]
cursive_core = { version = "0.4" }
tinyvec = "1.10"
unicode-segmentation = "1.10.1"
secure_buffer = { path = "../secure_buffer" }

[dev-dependencies]
cursive = { version = "0.21" }
